---
# Role to set up a PostgreSQL server for FOLIO
- name: Install prereqs from apt
  become: yes
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-virtualenv
    - python3-virtualenv
    - python-psycopg2
    - python3-psycopg2
    - python-pip
    - python3-pip
    - python-apt
    - python3-apt
    - ssl-cert

- name: Install apt key for PostgreSQL
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Install apt repository for PostgreSQL
  become: yes
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"

- name: Install postgresql from apt
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6

- name: Configure postgresql to listen on all interfaces
  become: yes
  lineinfile:
    dest: /etc/postgresql/9.6/main/postgresql.conf
    line: "listen_addresses = '*'"
    insertafter: 'Connection Settings'
  notify: Restart postgresql

- name: Set max number of postgresql connections
  become: yes
  lineinfile: 
    dest: /etc/postgresql/9.6/main/postgresql.conf
    regexp: '^max_connections\s*=\s*\d+.*$'
    line: "max_connections = {{ pg_max_conn }}"
    backrefs: yes 
  notify: Restart postgresql

- name: Configure postgresql to allow connections from all addresses
  become: yes
  lineinfile:
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    line: "host  all  all  0.0.0.0/0  md5"
  notify: Restart postgresql

# For now, this must be a SUPERUSER (cf. DMOD-250)
- name: Create a postgres admin user that can create roles and databases 
  become: yes
  become_user: postgres
  postgresql_user: 
    name: "{{ pg_admin_user }}"
    password: "{{ pg_admin_password }}"
    encrypted: yes
    # role_attr_flags: CREATEDB,CREATEROLE,LOGIN
    role_attr_flags: SUPERUSER
    
- meta: flush_handlers
